'use client';

import { useEffect } from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { setupWorker } from 'msw';
import { handlers } from '@/mocks/handlers';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	// msw mocking
	useEffect(() => {
		if (typeof window !== 'undefined') {
			const worker = setupWorker(...handlers);
			worker.start();
		}
	}, []);
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
};

export default RootLayout;
